import type { Goal, NutritionTarget } from '../types'

export type MealType = 'breakfast' | 'lunch_dinner' | 'snack'

export interface Meal {
  id: string
  name: string
  mealType: MealType
  ingredients: string[]
  instructions: string
  /** 1 = économique, 2 = un peu plus cher, 3 = occasionnel */
  costTier: 1 | 2 | 3
  calories: number
  protein_g: number
  carbs_g: number
  fat_g: number
}

export const MEALS: Meal[] = [
  // --- Petits-déjeuners ---
  {
    id: 'bf_oats_pb',
    name: "Porridge avoine, banane, beurre de cacahuète",
    mealType: 'breakfast',
    ingredients: ['60g flocons d\'avoine', '250ml lait demi-écrémé', '1 banane', '1 cuillère de beurre de cacahuète'],
    instructions: 'Fais chauffer les flocons dans le lait 3-4 min, ajoute la banane écrasée et le beurre de cacahuète.',
    costTier: 1,
    calories: 480,
    protein_g: 18,
    carbs_g: 65,
    fat_g: 15,
  },
  {
    id: 'bf_eggs_bread',
    name: 'Œufs brouillés et pain complet',
    mealType: 'breakfast',
    ingredients: ['3 œufs', '2 tranches de pain complet', 'un peu de beurre'],
    instructions: 'Brouille les œufs à la poêle avec un peu de beurre, sale, poivre, sers avec le pain grillé.',
    costTier: 1,
    calories: 420,
    protein_g: 24,
    carbs_g: 30,
    fat_g: 20,
  },
  {
    id: 'bf_skyr_granola',
    name: 'Skyr, granola et fruits rouges',
    mealType: 'breakfast',
    ingredients: ['300g skyr nature', '40g granola', 'fruits rouges surgelés'],
    instructions: 'Mélange le skyr avec le granola et les fruits rouges décongelés.',
    costTier: 2,
    calories: 380,
    protein_g: 32,
    carbs_g: 45,
    fat_g: 6,
  },
  {
    id: 'bf_fromage_blanc',
    name: 'Pain, fromage blanc et miel',
    mealType: 'breakfast',
    ingredients: ['2 tranches de pain', '200g fromage blanc 20%', '1 cuillère de miel'],
    instructions: 'Tartine le pain, sers le fromage blanc avec le miel à côté.',
    costTier: 1,
    calories: 350,
    protein_g: 18,
    carbs_g: 50,
    fat_g: 8,
  },
  {
    id: 'bf_omelette_fromage',
    name: 'Omelette au fromage et toast',
    mealType: 'breakfast',
    ingredients: ['3 œufs', '30g fromage râpé', '1 tranche de pain'],
    instructions: 'Bats les œufs, ajoute le fromage, cuis en omelette à la poêle.',
    costTier: 1,
    calories: 480,
    protein_g: 28,
    carbs_g: 25,
    fat_g: 28,
  },
  {
    id: 'bf_porridge_oeuf',
    name: "Porridge protéiné à l'œuf",
    mealType: 'breakfast',
    ingredients: ["50g flocons d'avoine", '200ml lait', '1 œuf', 'cannelle'],
    instructions: "Fais cuire les flocons dans le lait, incorpore l'œuf battu hors du feu en remuant vite, ajoute la cannelle.",
    costTier: 1,
    calories: 420,
    protein_g: 22,
    carbs_g: 55,
    fat_g: 12,
  },
  {
    id: 'bf_yaourt_muesli',
    name: 'Yaourts, muesli et banane',
    mealType: 'breakfast',
    ingredients: ['2 yaourts nature', '40g muesli', '1 banane'],
    instructions: 'Mélange le tout dans un bol.',
    costTier: 1,
    calories: 350,
    protein_g: 14,
    carbs_g: 55,
    fat_g: 8,
  },
  {
    id: 'bf_tartines_pb',
    name: 'Tartines beurre de cacahuète et banane',
    mealType: 'breakfast',
    ingredients: ['3 tranches de pain complet', '2 cuillères de beurre de cacahuète', '1 banane'],
    instructions: 'Tartine le pain, ajoute la banane en rondelles.',
    costTier: 1,
    calories: 450,
    protein_g: 15,
    carbs_g: 55,
    fat_g: 20,
  },
  {
    id: 'bf_pancakes_prot',
    name: 'Pancakes protéinés maison',
    mealType: 'breakfast',
    ingredients: ["80g flocons d'avoine mixés", '2 œufs', '1 banane écrasée', 'un peu de miel'],
    instructions: 'Mixe ou mélange tous les ingrédients, cuis en petites pancakes à la poêle 2-3 min de chaque côté.',
    costTier: 1,
    calories: 440,
    protein_g: 22,
    carbs_g: 55,
    fat_g: 14,
  },
  {
    id: 'bf_avocat_oeuf',
    name: 'Tartine avocat et œuf',
    mealType: 'breakfast',
    ingredients: ['2 tranches de pain complet', '1/2 avocat', '2 œufs (pochés ou durs)'],
    instructions: 'Écrase l\'avocat sur le pain grillé, ajoute les œufs coupés en tranches, sale, poivre.',
    costTier: 2,
    calories: 430,
    protein_g: 20,
    carbs_g: 35,
    fat_g: 24,
  },
  {
    id: 'bf_bowl_skyr_fruits_secs',
    name: 'Bowl skyr, flocons et fruits secs',
    mealType: 'breakfast',
    ingredients: ['300g skyr nature', '30g flocons d\'avoine', 'quelques fruits secs (raisins, abricots)'],
    instructions: 'Mélange le skyr avec les flocons et les fruits secs coupés.',
    costTier: 2,
    calories: 400,
    protein_g: 34,
    carbs_g: 45,
    fat_g: 6,
  },
  {
    id: 'bf_pain_perdu',
    name: 'Pain perdu maison (pain rassis)',
    mealType: 'breakfast',
    ingredients: ['3 tranches de pain rassis', '1 œuf', '150ml lait', 'cannelle', 'un peu de beurre'],
    instructions: 'Trempe le pain dans l\'œuf battu avec le lait et la cannelle, dore à la poêle avec un peu de beurre.',
    costTier: 1,
    calories: 400,
    protein_g: 16,
    carbs_g: 50,
    fat_g: 14,
  },
  {
    id: 'bf_muesli_maison',
    name: 'Muesli maison, lait et banane',
    mealType: 'breakfast',
    ingredients: ["50g flocons d'avoine", '250ml lait demi-écrémé', '1 banane', 'quelques amandes'],
    instructions: 'Mélange les flocons avec le lait, laisse gonfler 5 min, ajoute la banane et les amandes.',
    costTier: 1,
    calories: 420,
    protein_g: 16,
    carbs_g: 60,
    fat_g: 12,
  },
  {
    id: 'bf_smoothie_prot',
    name: 'Smoothie protéiné banane-avoine',
    mealType: 'breakfast',
    ingredients: ['1 banane', '250ml lait', '40g flocons d\'avoine', '1 cuillère de beurre de cacahuète'],
    instructions: 'Mixe tous les ingrédients au blender jusqu\'à texture lisse.',
    costTier: 1,
    calories: 460,
    protein_g: 17,
    carbs_g: 65,
    fat_g: 14,
  },
  {
    id: 'bf_galette_sarrasin',
    name: 'Galette de sarrasin jambon-fromage',
    mealType: 'breakfast',
    ingredients: ['1 galette de sarrasin', '1 tranche de jambon', '30g fromage râpé', '1 œuf'],
    instructions: 'Chauffe la galette à la poêle, garnis de jambon, fromage et œuf, plie en carré.',
    costTier: 1,
    calories: 420,
    protein_g: 26,
    carbs_g: 35,
    fat_g: 20,
  },
  {
    id: 'bf_pain_oeufs_simple',
    name: 'Pain, œufs au plat et fromage',
    mealType: 'breakfast',
    ingredients: ['2 tranches de pain', '2 œufs', '20g de fromage'],
    instructions: 'Cuis les œufs au plat, sers avec le pain et le fromage.',
    costTier: 1,
    calories: 380,
    protein_g: 20,
    carbs_g: 30,
    fat_g: 18,
  },

  // --- Déjeuners / dîners ---
  {
    id: 'ld_riz_poulet',
    name: 'Riz, poulet et légumes',
    mealType: 'lunch_dinner',
    ingredients: ['150g riz cru', '150g blanc de poulet', 'poêlée de légumes surgelés', 'filet d\'huile d\'olive'],
    instructions: 'Cuis le riz, saisis le poulet coupé en morceaux à la poêle, fais revenir les légumes, mélange le tout.',
    costTier: 1,
    calories: 650,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 15,
  },
  {
    id: 'ld_pates_bolo',
    name: 'Pâtes à la bolognaise maison',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g bœuf haché 5%', 'sauce tomate', 'oignon'],
    instructions: "Fais revenir l'oignon et le bœuf haché, ajoute la sauce tomate, laisse mijoter, sers sur les pâtes cuites.",
    costTier: 1,
    calories: 700,
    protein_g: 42,
    carbs_g: 85,
    fat_g: 18,
  },
  {
    id: 'ld_lentilles_oeuf',
    name: 'Lentilles corail et œufs',
    mealType: 'lunch_dinner',
    ingredients: ['150g lentilles corail', '2 œufs', 'oignon', 'épices (cumin, curry)'],
    instructions: 'Cuis les lentilles avec l\'oignon et les épices, sers avec les œufs durs ou au plat.',
    costTier: 1,
    calories: 550,
    protein_g: 30,
    carbs_g: 70,
    fat_g: 15,
  },
  {
    id: 'ld_riz_poulet_mais',
    name: 'Riz, poulet et maïs',
    mealType: 'lunch_dinner',
    ingredients: ['150g riz cru', '150g blanc de poulet', 'maïs', "filet d'huile d'olive"],
    instructions: "Cuis le riz, poêle le poulet coupé en dés, mélange avec le maïs égoutté et un filet d'huile d'olive.",
    costTier: 1,
    calories: 620,
    protein_g: 42,
    carbs_g: 75,
    fat_g: 12,
  },
  {
    id: 'ld_omelette_pdt',
    name: 'Omelette garnie et pommes de terre sautées',
    mealType: 'lunch_dinner',
    ingredients: ['4 œufs', 'pommes de terre', 'oignon', 'poivron'],
    instructions: 'Fais sauter les pommes de terre en dés avec l\'oignon et le poivron, verse les œufs battus par-dessus, cuis à couvert.',
    costTier: 1,
    calories: 600,
    protein_g: 32,
    carbs_g: 55,
    fat_g: 28,
  },
  {
    id: 'ld_dinde_riz',
    name: 'Escalope de dinde, riz et légumes',
    mealType: 'lunch_dinner',
    ingredients: ['150g escalope de dinde', '150g riz cru', 'légumes surgelés'],
    instructions: 'Poêle l\'escalope de dinde, cuis le riz, fais revenir les légumes, sers ensemble.',
    costTier: 1,
    calories: 600,
    protein_g: 45,
    carbs_g: 65,
    fat_g: 12,
  },
  {
    id: 'ld_chili',
    name: 'Chili con carne maison',
    mealType: 'lunch_dinner',
    ingredients: ['150g bœuf haché', 'haricots rouges en boîte', 'tomates concassées', '100g riz cru'],
    instructions: 'Fais revenir le bœuf haché, ajoute les haricots et les tomates, laisse mijoter 15 min, sers avec le riz.',
    costTier: 1,
    calories: 650,
    protein_g: 40,
    carbs_g: 70,
    fat_g: 18,
  },
  {
    id: 'ld_wrap',
    name: 'Wrap poulet et crudités',
    mealType: 'lunch_dinner',
    ingredients: ['2 tortillas', '150g blanc de poulet', 'fromage frais', 'crudités (salade, tomate, carotte râpée)'],
    instructions: 'Poêle le poulet, tartine les tortillas de fromage frais, garnis de poulet et crudités, roule.',
    costTier: 1,
    calories: 550,
    protein_g: 35,
    carbs_g: 55,
    fat_g: 18,
  },
  {
    id: 'ld_curry_pois_chiches',
    name: 'Curry de pois chiches et riz',
    mealType: 'lunch_dinner',
    ingredients: ['pois chiches en boîte', 'lait de coco léger', 'curry', '150g riz cru'],
    instructions: 'Fais revenir les pois chiches avec le curry, ajoute le lait de coco, laisse mijoter, sers avec le riz.',
    costTier: 1,
    calories: 600,
    protein_g: 20,
    carbs_g: 90,
    fat_g: 15,
  },
  {
    id: 'ld_steak_pates',
    name: 'Steak haché, pâtes et légumes',
    mealType: 'lunch_dinner',
    ingredients: ['steak haché 15%', '100g pâtes', 'légumes surgelés'],
    instructions: 'Cuis le steak haché à la poêle, cuis les pâtes, fais revenir les légumes, sers ensemble.',
    costTier: 1,
    calories: 650,
    protein_g: 38,
    carbs_g: 70,
    fat_g: 22,
  },
  {
    id: 'ld_pates_poulet_creme',
    name: 'Pâtes au poulet et crème légère',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g blanc de poulet', '10cl crème légère', 'champignons (frais ou en boîte)'],
    instructions: 'Poêle le poulet en dés, ajoute les champignons, déglace à la crème légère, sers sur les pâtes cuites.',
    costTier: 1,
    calories: 700,
    protein_g: 48,
    carbs_g: 75,
    fat_g: 20,
  },
  {
    id: 'ld_pates_poulet_curry',
    name: 'Poulet au curry et pâtes',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', '100g pâtes', 'curry en poudre', 'lait de coco léger'],
    instructions: 'Poêle le poulet, saupoudre de curry, ajoute un peu de lait de coco, laisse mijoter, sers sur les pâtes.',
    costTier: 1,
    calories: 680,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 18,
  },
  {
    id: 'ld_pates_pesto_poulet',
    name: 'Pâtes au pesto et poulet grillé',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g blanc de poulet', '2 cuillères de pesto', 'tomates cerises'],
    instructions: 'Grille le poulet à la poêle, mélange les pâtes cuites avec le pesto, ajoute le poulet coupé et les tomates.',
    costTier: 1,
    calories: 680,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 22,
  },
  {
    id: 'ld_poulet_fajitas',
    name: 'Poulet fajitas',
    mealType: 'lunch_dinner',
    ingredients: ['2 tortillas', '150g blanc de poulet', 'poivrons', 'oignon', 'épices fajitas'],
    instructions: 'Fais sauter le poulet en lanières avec poivrons, oignon et épices, garnis les tortillas.',
    costTier: 1,
    calories: 600,
    protein_g: 42,
    carbs_g: 60,
    fat_g: 16,
  },
  {
    id: 'ld_poulet_soja_riz',
    name: 'Poulet mariné soja-miel, riz et brocolis',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', 'sauce soja', 'un peu de miel', '150g riz cru', 'brocolis surgelés'],
    instructions: "Fais mariner le poulet dans soja+miel quelques minutes, poêle-le, cuis le riz et les brocolis à côté.",
    costTier: 1,
    calories: 620,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 10,
  },
  {
    id: 'ld_pates_carbo_legere',
    name: 'Pâtes à la carbonara légère (poulet ou lardons)',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g blanc de poulet ou lardons', '1 œuf', '30g parmesan'],
    instructions: 'Poêle le poulet ou les lardons, mélange hors du feu avec les pâtes chaudes, œuf battu et parmesan.',
    costTier: 1,
    calories: 700,
    protein_g: 48,
    carbs_g: 70,
    fat_g: 22,
  },
  {
    id: 'ld_poulet_basquaise',
    name: 'Poulet basquaise et riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', 'poivrons', 'tomates concassées', '150g riz cru'],
    instructions: 'Fais revenir le poulet et les poivrons, ajoute les tomates, laisse mijoter 15 min, sers avec le riz.',
    costTier: 1,
    calories: 620,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 10,
  },
  {
    id: 'ld_pates_poulet_tomate',
    name: 'Pâtes au poulet et tomates cerises',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g blanc de poulet', 'tomates cerises', 'ail', "filet d'huile d'olive"],
    instructions: "Poêle le poulet en dés avec l'ail et les tomates cerises, mélange avec les pâtes cuites.",
    costTier: 1,
    calories: 640,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 12,
  },
  {
    id: 'ld_poulet_roti_legumes',
    name: 'Poulet rôti, pâtes et légumes rôtis',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', '100g pâtes', 'légumes (courgette, poivron) au four'],
    instructions: 'Fais rôtir le poulet et les légumes au four, sers avec les pâtes cuites et un filet d\'huile d\'olive.',
    costTier: 1,
    calories: 650,
    protein_g: 45,
    carbs_g: 70,
    fat_g: 15,
  },
  {
    id: 'ld_pates_bolo_dinde',
    name: 'Pâtes à la bolognaise de dinde (version light)',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g dinde hachée', 'sauce tomate', 'oignon'],
    instructions: "Fais revenir l'oignon et la dinde hachée, ajoute la sauce tomate, laisse mijoter, sers sur les pâtes.",
    costTier: 1,
    calories: 620,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 10,
  },
  {
    id: 'ld_poulet_tikka_riz',
    name: 'Poulet tikka masala simplifié et riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', 'sauce tomate', 'yaourt nature', 'épices tikka/garam masala', '150g riz cru'],
    instructions: 'Poêle le poulet avec les épices, ajoute la sauce tomate et une cuillère de yaourt, laisse mijoter, sers avec le riz.',
    costTier: 1,
    calories: 640,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 12,
  },
  {
    id: 'ld_poulet_moutarde_riz',
    name: 'Poulet à la moutarde et riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', '1 cuillère de moutarde', '10cl crème légère', '150g riz cru'],
    instructions: 'Poêle le poulet, ajoute la moutarde et la crème légère, laisse épaissir, sers avec le riz.',
    costTier: 1,
    calories: 640,
    protein_g: 45,
    carbs_g: 70,
    fat_g: 16,
  },
  {
    id: 'ld_porc_riz_legumes',
    name: 'Sauté de porc, riz et légumes',
    mealType: 'lunch_dinner',
    ingredients: ['150g échine de porc en dés', '150g riz cru', 'légumes surgelés', 'sauce soja'],
    instructions: 'Poêle le porc en dés avec un peu de sauce soja, cuis le riz et les légumes, sers ensemble.',
    costTier: 1,
    calories: 650,
    protein_g: 40,
    carbs_g: 75,
    fat_g: 18,
  },
  {
    id: 'ld_couscous_poulet',
    name: 'Couscous poulet maison',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', '150g semoule', 'pois chiches en boîte', 'carottes, courgettes', 'épices couscous'],
    instructions: 'Fais mijoter le poulet avec les légumes et les épices, réhydrate la semoule à l\'eau chaude, sers ensemble.',
    costTier: 1,
    calories: 650,
    protein_g: 42,
    carbs_g: 80,
    fat_g: 12,
  },
  {
    id: 'ld_gratin_pates_poulet',
    name: 'Gratin de pâtes au poulet et fromage',
    mealType: 'lunch_dinner',
    ingredients: ['100g pâtes', '150g blanc de poulet', '20cl sauce béchamel (ou crème légère)', '50g fromage râpé'],
    instructions: 'Mélange les pâtes cuites, le poulet poêlé et la sauce, verse dans un plat, couvre de fromage, gratine au four 15 min.',
    costTier: 1,
    calories: 720,
    protein_g: 46,
    carbs_g: 70,
    fat_g: 26,
  },
  {
    id: 'ld_riz_cantonais',
    name: 'Riz cantonais maison',
    mealType: 'lunch_dinner',
    ingredients: ['150g riz cru', '2 œufs', '100g jambon ou blanc de poulet en dés', 'petits pois, carottes', 'sauce soja'],
    instructions: 'Cuis le riz à l\'avance (idéalement froid), fais revenir les légumes et le jambon, ajoute le riz et l\'œuf battu, sauce soja.',
    costTier: 1,
    calories: 650,
    protein_g: 32,
    carbs_g: 85,
    fat_g: 16,
  },
  {
    id: 'ld_haricots_saucisse',
    name: 'Haricots blancs et saucisse (cassoulet simplifié)',
    mealType: 'lunch_dinner',
    ingredients: ['haricots blancs en boîte', '2 saucisses de Toulouse', 'tomates concassées', 'oignon'],
    instructions: 'Poêle les saucisses coupées avec l\'oignon, ajoute les haricots et les tomates, laisse mijoter 15 min.',
    costTier: 1,
    calories: 680,
    protein_g: 32,
    carbs_g: 55,
    fat_g: 32,
  },
  {
    id: 'ld_dinde_provencale',
    name: 'Sauté de dinde à la provençale, riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g dinde en dés', 'tomates, courgettes', 'herbes de Provence', '150g riz cru'],
    instructions: 'Poêle la dinde avec les légumes et les herbes, laisse mijoter 10 min, sers avec le riz.',
    costTier: 1,
    calories: 600,
    protein_g: 45,
    carbs_g: 70,
    fat_g: 10,
  },
  {
    id: 'ld_omelette_jambon_pdt',
    name: 'Omelette jambon-fromage et pommes de terre',
    mealType: 'lunch_dinner',
    ingredients: ['4 œufs', '2 tranches de jambon', '30g fromage râpé', 'pommes de terre'],
    instructions: 'Fais sauter les pommes de terre en dés, verse les œufs battus avec jambon et fromage par-dessus, cuis à couvert.',
    costTier: 1,
    calories: 620,
    protein_g: 34,
    carbs_g: 50,
    fat_g: 30,
  },
  {
    id: 'ld_gratin_dauphinois_jambon',
    name: 'Gratin dauphinois au jambon',
    mealType: 'lunch_dinner',
    ingredients: ['pommes de terre', '2 tranches de jambon', '15cl crème légère', 'un peu de lait', 'fromage râpé'],
    instructions: 'Coupe les pommes de terre en fines rondelles, alterne avec le jambon dans un plat, couvre de crème/lait et fromage, four 45 min.',
    costTier: 1,
    calories: 620,
    protein_g: 24,
    carbs_g: 60,
    fat_g: 30,
  },
  {
    id: 'ld_chili_sin_carne',
    name: 'Chili sin carne (végétarien)',
    mealType: 'lunch_dinner',
    ingredients: ['haricots rouges en boîte', 'lentilles ou pois chiches', 'tomates concassées', '100g riz cru', 'épices chili'],
    instructions: 'Fais revenir les légumineuses avec les épices, ajoute les tomates, laisse mijoter 15 min, sers avec le riz.',
    costTier: 1,
    calories: 580,
    protein_g: 22,
    carbs_g: 95,
    fat_g: 8,
  },
  {
    id: 'ld_poulet_gratin_pdt',
    name: 'Poulet et pommes de terre gratinées au four',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', 'pommes de terre en tranches', 'un peu de crème légère', 'fromage râpé'],
    instructions: 'Dispose le poulet et les pommes de terre dans un plat, un peu de crème et de fromage par-dessus, four 35-40 min.',
    costTier: 1,
    calories: 650,
    protein_g: 42,
    carbs_g: 60,
    fat_g: 24,
  },
  {
    id: 'ld_boeuf_oignon_riz',
    name: 'Sauté de bœuf à l\'oignon, riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g bœuf en lamelles (bavette ou paleron)', 'oignons', 'sauce soja', '150g riz cru'],
    instructions: 'Poêle le bœuf vivement avec les oignons et un peu de sauce soja, sers avec le riz.',
    costTier: 2,
    calories: 620,
    protein_g: 42,
    carbs_g: 70,
    fat_g: 16,
  },
  {
    id: 'ld_croque_monsieur',
    name: 'Croque-monsieur maison et salade',
    mealType: 'lunch_dinner',
    ingredients: ['2 tranches de pain de mie', '2 tranches de jambon', '40g fromage râpé', 'salade verte'],
    instructions: 'Monte le croque avec jambon et fromage, dore à la poêle ou au four, sers avec la salade.',
    costTier: 1,
    calories: 550,
    protein_g: 28,
    carbs_g: 40,
    fat_g: 28,
  },
  {
    id: 'ld_quiche_lorraine',
    name: 'Quiche lorraine maison et salade',
    mealType: 'lunch_dinner',
    ingredients: ['1 pâte brisée', '3 œufs', '15cl crème légère', '100g lardons ou jambon', 'salade verte'],
    instructions: 'Fonce la pâte, verse le mélange œufs-crème-lardons, four 30-35 min, sers avec la salade.',
    costTier: 1,
    calories: 650,
    protein_g: 26,
    carbs_g: 45,
    fat_g: 38,
  },
  {
    id: 'ld_pois_chiches_epices_riz',
    name: 'Poêlée de pois chiches épicés et riz',
    mealType: 'lunch_dinner',
    ingredients: ['pois chiches en boîte', 'cumin, paprika', 'oignon', '150g riz cru'],
    instructions: 'Poêle les pois chiches avec l\'oignon et les épices quelques minutes, sers avec le riz.',
    costTier: 1,
    calories: 580,
    protein_g: 20,
    carbs_g: 95,
    fat_g: 8,
  },
  {
    id: 'ld_poulet_pane_pates',
    name: 'Escalope de poulet panée maison, pâtes',
    mealType: 'lunch_dinner',
    ingredients: ['150g escalope de poulet', 'chapelure', '1 œuf', '100g pâtes'],
    instructions: 'Pane l\'escalope (œuf puis chapelure), poêle-la des deux côtés, sers avec les pâtes.',
    costTier: 1,
    calories: 680,
    protein_g: 45,
    carbs_g: 75,
    fat_g: 18,
  },
  {
    id: 'ld_saucisse_lentilles',
    name: 'Saucisses et lentilles',
    mealType: 'lunch_dinner',
    ingredients: ['2 saucisses (Strasbourg ou Toulouse)', '150g lentilles vertes cuites', 'oignon', 'carotte'],
    instructions: 'Cuis les saucisses à la poêle ou à l\'eau, fais mijoter les lentilles avec oignon et carotte, sers ensemble.',
    costTier: 1,
    calories: 620,
    protein_g: 30,
    carbs_g: 55,
    fat_g: 28,
  },
  {
    id: 'ld_falafel_maison',
    name: 'Galettes de pois chiches (falafel maison) et pain pita',
    mealType: 'lunch_dinner',
    ingredients: ['pois chiches en boîte', 'ail, cumin, persil', '1 œuf', '2 pains pita', 'crudités'],
    instructions: 'Mixe les pois chiches avec ail, épices et œuf, forme des galettes, poêle-les, sers dans le pita avec crudités.',
    costTier: 1,
    calories: 600,
    protein_g: 22,
    carbs_g: 90,
    fat_g: 14,
  },
  {
    id: 'ld_fricassee_champignons_poulet',
    name: 'Fricassée de poulet aux champignons, riz',
    mealType: 'lunch_dinner',
    ingredients: ['150g blanc de poulet', 'champignons (frais ou en boîte)', '10cl crème légère', '150g riz cru'],
    instructions: 'Poêle le poulet et les champignons, ajoute la crème, laisse mijoter 5 min, sers avec le riz.',
    costTier: 1,
    calories: 650,
    protein_g: 45,
    carbs_g: 70,
    fat_g: 18,
  },

  // --- Collations ---
  {
    id: 'sn_grec_miel',
    name: 'Yaourt à la grecque et miel',
    mealType: 'snack',
    ingredients: ['1 yaourt à la grecque', '1 cuillère de miel'],
    instructions: 'Mélange et déguste.',
    costTier: 2,
    calories: 180,
    protein_g: 12,
    carbs_g: 18,
    fat_g: 6,
  },
  {
    id: 'sn_amandes_pomme',
    name: 'Poignée d\'amandes et une pomme',
    mealType: 'snack',
    ingredients: ['20g amandes', '1 pomme'],
    instructions: 'Tel quel.',
    costTier: 2,
    calories: 250,
    protein_g: 6,
    carbs_g: 25,
    fat_g: 15,
  },
  {
    id: 'sn_fromage_blanc_confiture',
    name: 'Fromage blanc et confiture',
    mealType: 'snack',
    ingredients: ['200g fromage blanc', '1 cuillère de confiture'],
    instructions: 'Mélange et déguste.',
    costTier: 1,
    calories: 180,
    protein_g: 12,
    carbs_g: 25,
    fat_g: 3,
  },
  {
    id: 'sn_banane_pb',
    name: 'Banane et beurre de cacahuète',
    mealType: 'snack',
    ingredients: ['1 banane', '1 cuillère de beurre de cacahuète'],
    instructions: 'Tartine la banane coupée en deux avec le beurre de cacahuète.',
    costTier: 1,
    calories: 250,
    protein_g: 6,
    carbs_g: 30,
    fat_g: 12,
  },
  {
    id: 'sn_oeufs_durs',
    name: 'Deux œufs durs',
    mealType: 'snack',
    ingredients: ['2 œufs'],
    instructions: 'Fais cuire 9-10 min à l\'eau bouillante.',
    costTier: 1,
    calories: 160,
    protein_g: 14,
    carbs_g: 2,
    fat_g: 10,
  },
  {
    id: 'sn_pain_fromage',
    name: 'Pain et fromage',
    mealType: 'snack',
    ingredients: ['1 tranche de pain', '30g de fromage'],
    instructions: 'Tel quel.',
    costTier: 1,
    calories: 280,
    protein_g: 12,
    carbs_g: 30,
    fat_g: 12,
  },
  {
    id: 'sn_compote_amandes',
    name: 'Compote sans sucre et amandes',
    mealType: 'snack',
    ingredients: ['1 compote sans sucre ajouté', '15g amandes'],
    instructions: 'Tel quel.',
    costTier: 1,
    calories: 170,
    protein_g: 3,
    carbs_g: 20,
    fat_g: 8,
  },
  {
    id: 'sn_barre_maison',
    name: 'Barre céréales maison',
    mealType: 'snack',
    ingredients: ["80g flocons d'avoine", '2 cuillères de miel', '1 cuillère de beurre de cacahuète'],
    instructions: 'Mélange le tout, tasse dans un moule, four 15 min à 180°C, découpe en barres une fois refroidi.',
    costTier: 1,
    calories: 220,
    protein_g: 6,
    carbs_g: 30,
    fat_g: 8,
  },
  {
    id: 'sn_smoothie_banane',
    name: 'Smoothie banane-lait',
    mealType: 'snack',
    ingredients: ['1 banane', '200ml lait demi-écrémé'],
    instructions: 'Mixe la banane avec le lait.',
    costTier: 1,
    calories: 200,
    protein_g: 8,
    carbs_g: 32,
    fat_g: 4,
  },
  {
    id: 'sn_fruits_secs',
    name: 'Poignée de fruits secs (dattes, abricots)',
    mealType: 'snack',
    ingredients: ['4-5 dattes ou abricots secs'],
    instructions: 'Tel quel.',
    costTier: 1,
    calories: 150,
    protein_g: 1,
    carbs_g: 35,
    fat_g: 0,
  },
  {
    id: 'sn_yaourt_banane',
    name: 'Yaourt nature et banane',
    mealType: 'snack',
    ingredients: ['2 yaourts nature', '1 banane'],
    instructions: 'Mélange le tout.',
    costTier: 1,
    calories: 200,
    protein_g: 10,
    carbs_g: 30,
    fat_g: 5,
  },
  {
    id: 'sn_toast_pain_epices',
    name: 'Pain d\'épices et fromage blanc',
    mealType: 'snack',
    ingredients: ['2 tranches de pain d\'épices', '150g fromage blanc'],
    instructions: 'Tel quel.',
    costTier: 1,
    calories: 230,
    protein_g: 10,
    carbs_g: 40,
    fat_g: 3,
  },
  {
    id: 'sn_houmous_legumes',
    name: 'Houmous maison et bâtonnets de légumes',
    mealType: 'snack',
    ingredients: ['pois chiches en boîte', 'un peu de tahini ou huile d\'olive', 'ail, citron', 'carotte, concombre'],
    instructions: 'Mixe les pois chiches avec ail, citron et huile, sers avec les bâtonnets de légumes.',
    costTier: 1,
    calories: 220,
    protein_g: 8,
    carbs_g: 25,
    fat_g: 10,
  },
  {
    id: 'sn_galette_riz_pb',
    name: 'Galettes de riz et beurre de cacahuète',
    mealType: 'snack',
    ingredients: ['3 galettes de riz soufflé', '1 cuillère de beurre de cacahuète'],
    instructions: 'Tartine les galettes de beurre de cacahuète.',
    costTier: 1,
    calories: 210,
    protein_g: 6,
    carbs_g: 25,
    fat_g: 10,
  },
]

/** Item fixe (pas de rotation) affiché quand le profil a activé "shake de protéine tous les jours". */
export const PROTEIN_SHAKE_MEAL: Meal = {
  id: 'supplement_shake',
  name: 'Shake protéiné',
  mealType: 'snack',
  ingredients: ['1 dose de whey (~30g)', '250-300ml eau ou lait', '3-5g de créatine (sans goût, tu peux la mettre dedans)'],
  instructions: "Au shaker, quand tu veux dans la journée (typiquement après la séance). Les BCAA se prennent plutôt pendant l'entraînement.",
  costTier: 2,
  calories: 130,
  protein_g: 24,
  carbs_g: 4,
  fat_g: 2,
}

export interface SuggestedMeal {
  slot: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'shake'
  slotLabel: string
  meal: Meal
}

const FRACTIONS: Record<Goal, { breakfast: number; lunch: number; dinner: number; snack: number }> = {
  gain_muscle: { breakfast: 0.22, lunch: 0.32, dinner: 0.28, snack: 0.18 },
  lose_fat_tone: { breakfast: 0.28, lunch: 0.37, dinner: 0.3, snack: 0.05 },
  maintain: { breakfast: 0.25, lunch: 0.35, dinner: 0.3, snack: 0.1 },
}

function pickClosest(candidates: Meal[], targetCalories: number, seed: number, exclude: string[] = []): Meal {
  const pool = candidates.filter((m) => !exclude.includes(m.id))
  const sorted = [...pool].sort((a, b) => {
    const scoreA = Math.abs(a.calories - targetCalories) + a.costTier * 15
    const scoreB = Math.abs(b.calories - targetCalories) + b.costTier * 15
    return scoreA - scoreB
  })
  const shortlist = sorted.slice(0, Math.min(4, sorted.length))
  return shortlist[((seed % shortlist.length) + shortlist.length) % shortlist.length]
}

/**
 * Propose des repas économiques dont la somme colle approximativement aux
 * objectifs du jour. Si `hasProteinShake` est vrai, le shake est ajouté en
 * item fixe (pas de rotation) et ses macros sont déduites des objectifs
 * avant de répartir le reste sur les 4 repas, pour ne pas compter deux fois
 * les mêmes calories/protéines.
 */
export function suggestDailyMeals(targets: NutritionTarget, goal: Goal, seed = 0, hasProteinShake = false): SuggestedMeal[] {
  const fractions = FRACTIONS[goal]
  const mains = MEALS.filter((m) => m.mealType === 'lunch_dinner')
  const remainingCalories = hasProteinShake ? Math.max(0, targets.calories - PROTEIN_SHAKE_MEAL.calories) : targets.calories

  const breakfast = pickClosest(
    MEALS.filter((m) => m.mealType === 'breakfast'),
    remainingCalories * fractions.breakfast,
    seed,
  )
  const lunch = pickClosest(mains, remainingCalories * fractions.lunch, seed)
  const dinner = pickClosest(mains, remainingCalories * fractions.dinner, seed + 1, [lunch.id])
  const snack = pickClosest(
    MEALS.filter((m) => m.mealType === 'snack'),
    remainingCalories * fractions.snack,
    seed,
  )

  const result: SuggestedMeal[] = [
    { slot: 'breakfast', slotLabel: 'Petit-déjeuner', meal: breakfast },
    { slot: 'lunch', slotLabel: 'Déjeuner', meal: lunch },
    { slot: 'dinner', slotLabel: 'Dîner', meal: dinner },
    { slot: 'snack', slotLabel: 'Collation', meal: snack },
  ]

  if (hasProteinShake) {
    result.push({ slot: 'shake', slotLabel: 'Shake protéiné (fixe)', meal: PROTEIN_SHAKE_MEAL })
  }

  return result
}
